CREATE TABLE IF NOT EXISTS CURRENCY (
  ID      BIGINT         NOT NULL AUTO_INCREMENT
  ,
  CAPTION VARCHAR(10)    NOT NULL UNIQUE
  ,
  RATE    DECIMAL(10, 6) NOT NULL DEFAULT 0
  ,
  VERSION INT            NOT NULL DEFAULT 0
  ,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS COMPANY (
  ID      BIGINT       NOT NULL AUTO_INCREMENT
  ,
  CAPTION VARCHAR(255) NOT NULL UNIQUE
  ,
  VERSION INT          NOT NULL DEFAULT 0
  ,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CITY (
  ID      BIGINT      NOT NULL AUTO_INCREMENT
  ,
  CAPTION VARCHAR(60) NOT NULL UNIQUE
  ,
  VERSION INT         NOT NULL DEFAULT 0
  ,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SITE (
  ID      BIGINT       NOT NULL AUTO_INCREMENT
  ,
  CAPTION VARCHAR(60)  NOT NULL UNIQUE
  ,
  ALIAS   VARCHAR(60)  NOT NULL UNIQUE
  ,
  URL     VARCHAR(100) NOT NULL UNIQUE
  ,
  VERSION INT          NOT NULL DEFAULT 0
  ,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SITES_IDS_CITIES (
  ID        BIGINT NOT NULL AUTO_INCREMENT
  ,
  SITE_ID   BIGINT NOT NULL
  ,
  CITY_ID   BIGINT NOT NULL
  ,
  ID_REGION INT    NOT NULL
  ,
  VERSION   INT    NOT NULL DEFAULT 0
  ,
  PRIMARY KEY (ID)
  ,
  UNIQUE UQ_SITES_IDS_CITIES_1 (SITE_ID, CITY_ID)
  ,
  CONSTRAINT FK_SITES_IDS_CITIES_SITE FOREIGN KEY (SITE_ID)
  REFERENCES SITE (ID)
  ,
  CONSTRAINT FK_SITES_IDS_CITIES_CITY FOREIGN KEY (CITY_ID)
  REFERENCES CITY (ID)
);

CREATE TABLE IF NOT EXISTS VACANCY (
  ID          VARCHAR(2000) NOT NULL
  ,
  SITE_ID     BIGINT        NOT NULL
  ,
  URL         VARCHAR(2000) NOT NULL
  ,
  CAPTION     VARCHAR(255)  NOT NULL
  ,
  COMPANY_ID  BIGINT        NOT NULL
  ,
  CITY_ID     BIGINT
  ,
  REG_DATE    DATE
  ,
  PRICE_MIN   INT                    DEFAULT 0
  ,
  PRICE_MAX   INT                    DEFAULT 0
  ,
  CURRENCY_ID BIGINT                 DEFAULT 1
  ,
  VERSION     INT           NOT NULL DEFAULT 0
  ,
  PRIMARY KEY (ID)
  ,
  CONSTRAINT FK_VACANCY_COMPANY FOREIGN KEY (COMPANY_ID)
  REFERENCES COMPANY (ID)
  ,
  CONSTRAINT FK_VACANCY_CITY FOREIGN KEY (CITY_ID)
  REFERENCES CITY (ID)
  ,
  CONSTRAINT FK_VACANCY_SITE FOREIGN KEY (SITE_ID)
  REFERENCES SITE (ID)
  ,
  CONSTRAINT FK_VACANCY_CURRENCY FOREIGN KEY (CURRENCY_ID)
  REFERENCES CURRENCY (ID)
);

CREATE TABLE IF NOT EXISTS VIEWED_VACANCY (
  ID      BIGINT        NOT NULL AUTO_INCREMENT
  ,
  URL     VARCHAR(2000) NOT NULL
  ,
  VIEWED  BOOLEAN       NOT NULL DEFAULT TRUE
  ,
  VERSION INT           NOT NULL DEFAULT 0
  ,
  PRIMARY KEY (ID)
  ,
  CONSTRAINT UK_VIEWED_VACANCY_URL UNIQUE (URL)
);